# Unique name for your app container
name: app

# Runtime environment
type: python:3.11

# How much persistent disk you want (used if you save files locally)
disk: 1024

# Build phase: install dependencies
hooks:
  build: |
    pip install -r requirements.txt

# Web process (how to start FastAPI)
web:
  commands:
    start: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at. 
mounts:
  "web/uploads": "shared:files"
